CREATE DATABASE school_db; USE school_db;
CREATE DATABASE school_db; USE school_db;
CREATE TABLE enrollments ( enrollment_id INT PRIMARY KEY, student_id INT, class_id INT );
INSERT INTO enrollments (enrollment_id, student_id, class_id) VALUES (1, 1001, 2001);
INSERT INTO enrollments (enrollment_id, student_id, class_id) VALUES (2, 1002, 2002);
INSERT INTO enrollments (enrollment_id, student_id, class_id) VALUES (3, 1003, 2003);
ALTER TABLE enrollments ADD school_year VARCHAR(20);
CREATE TABLE classes ( id INT, class_name VARCHAR(50), room_no INT );
INSERT INTO classes (id, class_name, room_no) VALUES(01,'BSIT-2104',1111), (02,'BSIT-2105',2222), (03,'BSIT-2106',3333);
ALTER TABLE classes ADD COLUMN teacher_id INT;
ALTER TABLE classes ADD CONSTRAINT fk_classes_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id);
UPDATE classes SET room_no = 4444 WHERE id = 03;
